### ISSUE TITLE
Track regressions and unfinished contracts from #435–#437 and #439

### ISSUE THREAD

**Issue by SoymilkWinsAgain** [TARPS-group/prob-pipe#446]
## One-line summary

Repair regressions and incomplete contracts from #435–#437 and #439, separating independent runtime fixes from design decisions and implementation work carried by #444.

## Motivation and audit baseline

The merged stack is partially complete. Historical execution identified **three existing workflows that start failing in #436**, additional defects in the new kinds and aggregation, and two accepted contracts that were never implemented.

Acceptance was checked against the commitments at merge time, using #434 as the accepted baseline:

| Boundary | Commit | Audit conclusion |
|---|---|---|
| #434, accepted baseline | d96411fbcde3ba63853d17f79f1bd13f878fbcae | Context only; not re-audited as part of this issue |
| #435 | b59fe2c7891a2142acd3b6a380f3841799e961ad | New kinds largely work; native-scalar storage is defective |
| #436 | 8a9d1dfe1d98b3cf0717e78880cd4af1b86b59e0 | Kind-directed outputs implemented, with three confirmed regressions |
| #437 | 405dd68c738c672322f58fc00d38c3f10f58656a | Many integration gaps fixed; executor consistency and declaration preservation remain incomplete |
| #439, audited endpoint | 55af8497fb5692c35180f93c96316535a178778f | Scoped naming/constructor/axis-partition migration passed the checks; no independent new regression confirmed |

Each merge was examined relative to its first parent, followed by the combined stack. Public behavioral probes ran against all five package snapshots with the same dependencies, adapting constructor spelling where necessary.

The [#434 design baseline](https://github.com/TARPS-group/prob-pipe/pull/434) and the [closing comment on #398](https://github.com/TARPS-group/prob-pipe/issues/398#issuecomment-5387759834) explicitly include raw access and tracked batch selection. Their absence is an unfinished commitment, not a newly introduced legacy regression. The later target design in #444 changes some of those semantics; the implementation should follow the finalized new contract rather than first rebuilding an obsolete intermediate API.

## Dependencies and work split

- **A: Independent runtime fixes.** These can be addressed against the audited runtime without waiting for #444 or adopting its new architecture. A1 and A5 overlap future execution/spec work, but the underlying correctness requirements already apply today.
- **B: Design work and deferred implementation through #444.** Finalize the relevant contracts in #444 and implement those contracts in follow-up code PRs. Some requirements are already decided; they need an explicit implementation handoff rather than another design decision.
- Completing the documentation portion does **not** close runtime items. Each item below needs its own acceptance evidence.
- Design refinement can continue while A is repaired. Keep fixes scoped; no unrelated refactoring or compatibility layer is required by this issue.

## A. Independent runtime fixes

The snippets below target the audited endpoint and share this setup:

```python
import jax
import jax.numpy as jnp
import numpy as np
import probpipe as p

key = jax.random.PRNGKey(0)
rows = p.RecordBatch(
    "inputs", {"x": jnp.arange(3.)}, "row",
    element_spec=p.EventTemplate(x=()),
)
law = p.Normal(0., 1., name="x")
```

### A1 — P1: tracked numeric row results break auto/JAX sweeps

**Classification:** introduced regression, #436; persists after #437/#439.

```python
def score(mode):
    return p.Function(
        func=lambda r: p.log_prob(law, r["x"]),
        name="score", dispatch=mode,
    )(rows)

score("sequential")  # succeeds
score("auto")        # TypeError
score("jax")         # TypeError
```

Actual error: `_make_stack cannot aggregate output of type NumericArray; expected a list, jnp.ndarray, or batched Record.`

Expected: all supported RecordBatch dispatch paths produce the same numeric batch, levels and declaration. For this example the density values are approximately `[-0.9189385, -1.4189385, -2.9189386]`.

All three modes succeed at #434/#435. Auto/JAX fail at #436 and both later boundaries. This is not the explicitly deferred JAX vectorization of single-store **inputs**: the input here is a RecordBatch.

The [mapped row adapter](https://github.com/TARPS-group/prob-pipe/blob/55af8497fb5692c35180f93c96316535a178778f/probpipe/core/_workflow_sweep.py#L343) leaves NumericArray results intact, while the [mapped-output aggregator](https://github.com/TARPS-group/prob-pipe/blob/55af8497fb5692c35180f93c96316535a178778f/probpipe/core/_broadcast_distributions.py#L1081) does not handle them.

- [x] **Done when:** raw numeric, explicitly tracked numeric, and operation-produced numeric rows work across auto/sequential/JAX for supported RecordBatch inputs, with independently checked values and preserved levels/specs. Include multilevel inputs.

### A2 — P2: sample requires attributes outside SupportsSampling

**Classification:** introduced regression, #436; persists to the endpoint.

```python
class Sampler:
    _sampling_cost = "low"
    _preferred_orchestration = None

    def _sample(self, key, sample_shape=()):
        return jnp.ones(sample_shape)

s = Sampler()
assert isinstance(s, p.SupportsSampling)
p.sample(s, key=key)
p.sample(s, key=key, sample_shape=(2,))
```

Each sampling call raises `AttributeError: 'Sampler' object has no attribute 'name'`. Both work at #434/#435 and fail from #436 onward.

The [sampling boundary](https://github.com/TARPS-group/prob-pipe/blob/55af8497fb5692c35180f93c96316535a178778f/probpipe/core/ops.py#L121) unconditionally reads `name` and `name_is_auto`, which the structural protocol does not require. The explicit key isolates this regression from automatic-key behavior.

- [x] **Done when:** structural-only samplers supported by the current protocol work for scalar and batched explicit-key sampling without unpromised identity attributes. Existing named distributions retain correct result identity.

The new operation architecture's operand-admission contract is a separate design question under B3; it must not be used to silently narrow the current protocol while fixing this regression.

### A3 — P2: batched empirical sampling flattens opaque event axes

**Classification:** introduced regression, #436; persists to the endpoint.

```python
pairs = p.EmpiricalDistribution([("a", "b"), ("c", "d")], name="pairs")
p.sample(pairs, key=key, sample_shape=(3,))
```

Expected: three draws, each retaining its two-element opaque event. Actual: `ValueError: _make_stack got 6 outputs but expected prod(batch_shape)=3`.

A single draw succeeds. Sample shapes `(1,)`, `(3,)`, and `(2, 3)` work at #434/#435 and fail from #436 onward. The [object-draw path](https://github.com/TARPS-group/prob-pipe/blob/55af8497fb5692c35180f93c96316535a178778f/probpipe/core/ops.py#L187) flattens both leading draw axes and trailing event axes.

- [x] **Done when:** only sampling axes determine draw cardinality; each complete opaque event is preserved for scalar and multidimensional sample shapes. Verify event contents and shapes as well as batch levels.

### A4 — P2: native NumPy scalars are converted and can overflow at construction

**Classification:** defect in functionality introduced by #435, not a regression of an older NumericArray API.

With `jax_enable_x64=False`:

```python
p.NumericArray("large", np.float64(1e100)).value
# JAX float32 inf

p.NumericArray("large", np.asarray(1e100)).value
# Original NumPy float64 zero-dimensional array, finite 1e100
```

NumPy complex128 scalars likewise become complex64 with infinite components. NumPy float32 scalars remain native. The large-value reproducer emits an overflow warning.

The [constructor's builtin-scalar check](https://github.com/TARPS-group/prob-pipe/blob/55af8497fb5692c35180f93c96316535a178778f/probpipe/core/_numeric_array.py#L122) also matches NumPy float64/complex128 scalars. This violates #435's promise to preserve native representation and defer conversion to the compute boundary.

- [x] **Done when:** native scalar representation, dtype and finite values survive wrapping; actual builtin scalars retain their intended normalization. Tests distinguish construction from later backend conversion.

### A5 — P2: aggregation erases authoritative element declarations

**Classification:** new functionality/integration defect: numeric rows in #436; object-batch rows added in #437.

```python
from probpipe.core.constraints import positive

declared = p.NumericArraySpec((), dtype=np.float64, support=positive)
a = p.NumericArray("held", jnp.asarray(1., dtype=jnp.float32), spec=declared)
out = p.Function(
    func=lambda r: a, name="values", dispatch="sequential",
)(rows)
print(out.element_spec)
# dtype=float32, support=None; the input declaration was float64/positive
```

The held float32 value is admitted by the existing same-kind validation rule; the source declaration remains authoritative.

Two other reproduced cases return identically declared inner batches from each swept row:

| Returned row declaration | Aggregated declaration |
|---|---|
| OpaqueBatch with `OpaqueSpec(meta="authoritative")` | `OpaqueSpec(meta=None)` |
| FunctionBatch with `FunctionSpec(input_template=EventTemplate(x=()), output_spec=NumericArraySpec(()))` | `FunctionSpec(input_template=None, output_spec=None)` |

The [object aggregation branch](https://github.com/TARPS-group/prob-pipe/blob/55af8497fb5692c35180f93c96316535a178778f/probpipe/core/_broadcast_distributions.py#L903) verifies matching specs and then omits the spec when constructing the aggregate. The [numeric-row branch](https://github.com/TARPS-group/prob-pipe/blob/55af8497fb5692c35180f93c96316535a178778f/probpipe/core/_broadcast_distributions.py#L1023) re-infers it from backend arrays.

This is not an old object-batch regression: earlier stack stages did not preserve that row kind and its inner levels correctly in the first place.

- [x] **Done when:** aggregation retains agreed explicit declarations, including dtype/support, opaque metadata and function input/output declarations. Incompatible declarations receive the specified validation; inference applies only where appropriate for undeclared data. Verify downstream use, not just shape/type.

### A6 — P3: mixed batch/scalar rows produce an order-dependent NameError

**Classification:** validation defect introduced in #437; persists to the endpoint.

```python
inner = p.NumericArrayBatch(
    "inner", jnp.arange(2.), "inner",
    element_spec=p.NumericArraySpec(()),
)

def mixed(r):
    return 1. if float(r["x"]) == 0. else inner

p.Function(func=mixed, name="mixed", dispatch="sequential")(rows)
```

Actual: `NameError: cannot access free variable 'family' where it is not associated with a value in enclosing scope`. Putting a batch first instead produces the intended TypeError explaining mixed batch/non-batch rows.

The [batch-family validation](https://github.com/TARPS-group/prob-pipe/blob/55af8497fb5692c35180f93c96316535a178778f/probpipe/core/_broadcast_distributions.py#L688) initializes its local family only if the first row is a batch, although its caller enters when any row is a batch.

- [x] **Done when:** mixed rows produce the same actionable schema error in either order, without leaking NameError. Test a real sweep; the old direct-list-return reproducer is not a future contract, because #444 changes ordinary sequence wrapping.

### B1 — P2 unfinished commitment: raw access and operation opt-out

The #434 baseline promises `Batch.raw()`, operation-level `raw=True`, and raw access to held values. At the audited endpoint:

```python
p.sample(law, key=key, raw=True)  # unexpected keyword argument
rows.raw()                       # missing attribute
```

NumericArray/Opaque expose `.value`, not the specified raw interface. These omissions persisted throughout the stack; they were not newly broken old APIs. Function.apply is plain point evaluation, not an equivalent workflow-aware raw control.

**Handle through #444:** implement the finalized uniform `raw()` and detached-result boundary, including batch storage views and the appropriate Function/operation control interfaces. Do not first add an obsolete property/method split or treat an operation's raw control as an arbitrary wrapped callable argument.

- [ ] **Design done when:** #444 states one consistent per-kind raw contract, its identity/provenance behavior, the batch storage view, and how callers select raw execution.
- [ ] **Implementation done when:** every covered kind and operation exposes that contract, with scalar/batched and nested results tested. Merging #444 alone does not complete this item.

### B2 — P2 unfinished commitment: uniformly tracked batch access and kind resolution

At the audited endpoint:

```python
p.OpaqueBatch("labels", ["north"], "site")[0]          # str
p.FunctionBatch("functions", [lambda x: x], "site")[0]  # bare callable
rows["x"]                                           # bare JAX array
```

The baseline requires tracked element/column forms. Numeric columns lose named multiplicity when returned as bare arrays. NumericArrayBatch element selection does provide a tracked NumericArray.

The [object selection hook](https://github.com/TARPS-group/prob-pipe/blob/55af8497fb5692c35180f93c96316535a178778f/probpipe/core/_object_batch.py#L149) returns storage unconditionally; the [numeric column path](https://github.com/TARPS-group/prob-pipe/blob/55af8497fb5692c35180f93c96316535a178778f/probpipe/core/_record_batch.py#L371) returns a bare column. The registry also leaves the tracked side of FunctionSpec unregistered; its lookup returns None despite Function being the tracked callable kind. No separate public failure is attributed solely to that currently unused lookup.

**Handle through #444:** the identity contract has changed. The old baseline retained the exact stored tracked object on selection; #444 requires a selection **view** even when storage contains an already tracked object, retaining the original as a source. Implement the new rule directly.

- [ ] **Design done when:** #444 consistently specifies view identity, source provenance, numeric column levels/specs, and the spec-to-tracked-kind correspondence, without retaining the old “return the source object itself” rule.
- [ ] **Implementation done when:** raw and already tracked stored elements both yield the specified tracked views; numeric columns preserve their batch structure; the kind resolver agrees with the contract.

### B3 — Clarify the new operation admission boundary and preserve regression obligations

**Handle through #444, without blocking A's current-runtime fixes:**

- [ ] State how a structural-only capability object enters an operation that must plan its result declaration before execution. Does it provide declared metadata directly, require normalization/adaptation, or fall outside that operation's admitted operands? Separate this from SupportsSampling's method contract. Unsupported inputs need an explicit applicability error, not accidental identity-attribute access (A2).
- [ ] Carry A1/A5 into the acceptance criteria for spec migration and compiled execution: planning, mapped transport and result reconstruction must preserve the authoritative declaration, with consistent results across supported dispatches. The new architecture provides a place to enforce this; renaming spec classes does not fix it.
- [ ] State and test the new ordinary-sequence return rule separately from actual batch aggregation. A6 must remain covered by genuine mixed sweep rows; old list-to-batch expectations should not be reinstated.

Design comparison used #444 at `dde85ae857529a1ce5be3ee142a9af0383df82c7`:
[identity and batch views](https://github.com/TARPS-group/prob-pipe/blob/dde85ae857529a1ce5be3ee142a9af0383df82c7/design/02-shared-abstractions.md),
[wrapping and dispatch](https://github.com/TARPS-group/prob-pipe/blob/dde85ae857529a1ce5be3ee142a9af0383df82c7/design/04-functions.md),
[operation planning and raw controls](https://github.com/TARPS-group/prob-pipe/blob/dde85ae857529a1ce5be3ee142a9af0383df82c7/design/05-operations.md).

## Explicitly out of scope

- Reopening #434's accepted implementation.
- Treating all of #443/#444's target architecture as a merge-time obligation of this stack.
- Full explicit JAX vectorization over NumericArrayBatch/OpaqueBatch/FunctionBatch inputs, deliberately deferred in #437.
- Distribution-side naming work already tracked in #427.
- Re-reporting the older raw Record pytree issue #406 or the record-empirical sampling contract discussion #393 as newly introduced by these PRs.
- Counting defects fixed later within the same stack as outstanding.
- Broad refactors, new dependencies, or freezing obsolete sequence/selection semantics for compatibility.

Implementation PRs should reference this issue and close only their corresponding checklist items. Keep the tracking issue open until independent fixes and the agreed design-dependent implementations have their acceptance evidence.
